language: objective-c
install:
  - bundle install
  - brew outdated carthage || brew upgrade carthage
script:
  - ./Scripts/ci.sh
matrix:
  include:
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="iOS_10,watchOS_3";
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="iOS_11,watchOS_4";
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="iOS_12,watchOS_5";
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="iOS_13,watchOS_6";
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="macOS_10_15";
    after_success:
       bash <(curl -s https://codecov.io/bash) -J '^Valet$' -D .build/derivedData -t 5165deef-da9c-443d-90ea-bb0620bffe44
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="tvOS_10";
    after_success:
       bash <(curl -s https://codecov.io/bash) -J '^Valet$' -D .build/derivedData -t 5165deef-da9c-443d-90ea-bb0620bffe44
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="tvOS_11";
    after_success:
       bash <(curl -s https://codecov.io/bash) -J '^Valet$' -D .build/derivedData -t 5165deef-da9c-443d-90ea-bb0620bffe44
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="tvOS_12";
    after_success:
       bash <(curl -s https://codecov.io/bash) -J '^Valet$' -D .build/derivedData -t 5165deef-da9c-443d-90ea-bb0620bffe44
  - osx_image: xcode11.3
    env: ACTION="xcode";PLATFORMS="tvOS_13";
    after_success:
       bash <(curl -s https://codecov.io/bash) -J '^Valet$' -D .build/derivedData -t 5165deef-da9c-443d-90ea-bb0620bffe44
  - osx_image: xcode11.3
    env: ACTION="swift-package";PLATFORMS="iOS_13,tvOS_13,macOS_10_15,watchOS_6";
  - osx_image: xcode11.3
    env: ACTION="pod-lint";SWIFT_VERSION="5.0"
  - osx_image: xcode11.3
    env: ACTION="carthage"

branches:
  only:
  - master
  - develop--4.0
